- Form/Type/VichFileType.php
$options is not used within the event listener function
> Remove an unused parameter

- Resources/translations/VichUploaderBundle.ru.yml
- Resources/translations/VichUploaderBundle.uk.yml
> Translate to "ru" locale

- Storage/FlysystemStorage.php
Similar to https://github.com/thephpleague/flysystem/issues/72
> Use r instead of r+

- Resources/translations/VichUploaderBundle.de.yml
> Adding german translations

- .travis.yml
Travis use outdated version of Composer, better to update it first
> Self update Composer before install packages

- Tests/Twig/Extension/UploaderExtensionTest.php
- Twig/Extension/UploaderExtension.php
> remove deprecation warning while creating twig function

- Form/Type/VichFileType.php
- Resources/doc/form/vich_file_type.md
My staging server does not have all the files always on the server itself, thus making most of my forms not render at all.
> Make resolving of paths optional for delete link in VichFileType

- Mapping/PropertyMapping.php
> Correct FQCN

- Form/Type/VichFileType.php
> Add error_bubbliing option

- Resources/doc/usage.md
This should be the same behaviour as the Doctrine entity generator would create.
> Add return value to setter in example

- Naming/DirectoryNamerInterface.php
Quick typo fix : Propertymapping PropertyMapping
> PropertyMapping fix

- Resources/doc/form/vich_file_type.md
- Resources/doc/form/vich_image_type.md
Add information about the use of forms in Symfony3
> Update documentation for Symfony3

- Resources/translations/VichUploaderBundle.es.yml
> Spanish translation

- Resources/doc/form/vich_image_type.md
> documentation

- Resources/doc/usage.md
> fix for deprecation in documentattion

- composer.json
> Better dependencies with caret instead of tilde

- EventListener/Doctrine/UploadListener.php
Alternatively: https://styleci.io/ :)
> Consistent white space

- Event/Events.php
- Mapping/Annotation/Uploadable.php
- Mapping/Annotation/UploadableField.php
see https://github.com/symfony/symfony/pull/12299 for more information about event annotation
> Add annotations

- Resources/doc/usage.md
It is widely accepted that value objects should be immutable. Reflecting this in your docs will encourage people to do so and make the world a better place.
> Use DateTimeImmutable

- UPGRADE.md
Related to https://github.com/dustin10/VichUploaderBundle/issues/562
> Added upgrade docs from 0.13 to 1.0, to master

- composer.json
Haven't see any usage of the proxy-manager in this bundle. Let's try remove and build on Travis.
> Remove proxy-manager dependency

- Handler/AbstractHandler.php
- Mapping/Annotation/UploadableField.php
- Mapping/PropertyMapping.php
- Mapping/PropertyMappingFactory.php
- Metadata/Driver/AnnotationDriver.php
- Metadata/Driver/XmlDriver.php
- Metadata/Driver/YamlDriver.php
- Resources/doc/mapping/xml.md
- Resources/doc/mapping/yaml.md
- Resources/doc/usage.md
- Storage/AbstractStorage.php
- Tests/DummyEntity.php
- Tests/Mapping/PropertyMappingTest.php
- Tests/Metadata/Driver/AnnotationDriverTest.php
- Tests/Metadata/Driver/YamlDriverTest.php
- Tests/Storage/FileSystemStorageTest.php
- Tests/Storage/FlysystemStorageTest.php
- Tests/Storage/GaufretteStorageTest.php
- Tests/TwoFieldsDummyEntity.php
- Util/ClassUtils.php
> Added possibility store file info #413, #534

- Form/Type/VichFileType.php
- Form/Type/VichImageType.php
- Resources/doc/form/vich_file_type.md
- Resources/doc/form/vich_image_type.md
- Tests/Vich/UploaderBundle/Tests/Form/Type/VichFileTypeTest.php
- Tests/Vich/UploaderBundle/Tests/Form/Type/VichImageTypeTest.php
Useful for serving protected files via controller.
> Allow pass download_uri value into form types

- Tests/Util/FilenameUtilsTest.php
- Util/ClassUtils.php
- Util/FilenameUtils.php
- Util/Transliterator.php
Remove not needed inheritance and fix pathinfo for cyrilic filenames https://3v4l.org/pCkom
Waiting for Travis
> Fix transliterator refactoring

- Form/Type/VichImageType.php
- Tests/Vich/UploaderBundle/Tests/Form/Type/VichFileTypeTest.php
- Tests/Vich/UploaderBundle/Tests/Form/Type/VichImageTypeTest.php
Waiting for Travis. Closes #719 and covered with new test cases.
> Fix edge case when "download_uri" variable is not defined

- composer.json
Let's try wait for Travis build
> Remove some unused dependencies

- Metadata/Driver/AnnotationDriver.php
- Metadata/Driver/XmlDriver.php
- Metadata/Driver/YamlDriver.php
- Resources/doc/usage.md
> Fix method signatures

- DependencyInjection/VichUploaderExtension.php
- Tests/DependencyInjection/VichUploaderExtensionTest.php
> Fix form theme override

- Resources/doc/storage/gaufrette.md
- composer.json
- Added information about Gaufrette with Doctrine adapter dependency on `ocramius/proxy-manager`. 
- Added sugggestion to `composer.json`
> Added info about Gaufrette with Doctrine adapter

- DependencyInjection/VichUploaderExtension.php
- Resources/config/templating.xml
This tries to fix the issue spotted by @garak here -> https://github.com/dustin10/VichUploaderBundle/issues/788#issuecomment-342871863
> Fix some Symfony 4 autowiring issues

- DependencyInjection/VichUploaderExtension.php
@garak Havn't tested it yet, but I mean this. For now we can depends on the interface when using autowire and proper implementation would be injected.
> Add FQCN alias for storage

- DependencyInjection/Compiler/RegisterMappingDriversPass.php
- Resources/config/mapping.xml
- VichUploaderBundle.php
- composer.json
Just proof of concept for now. Continuation of discussion https://github.com/dustin10/VichUploaderBundle/pull/711#issuecomment-307930721
> [POC] Make yaml and annotations are optional

- Resources/doc/usage.md
Make it clear to use the VichFileType  and not the native Symfony FileType.
> Make docs more clear.

- Resources/translations/VichUploaderBundle.fi.yml
Added support for Finnish language.
> Add Finnish language translation file

- Resources/translations/VichUploaderBundle.ca.yml
> Add catalan translation

- Naming/CurrentDateTimeDirectoryNamer.php
- Resources/doc/namers.md
- phpunit.xml.dist
> deprecate non-property use of CurrentDateTimeDirectoryNamer

- Twig/Extension/UploaderExtension.php
- composer.json
See https://github.com/localheinz/composer-normalize
> Normalize composer

- Form/Type/VichFileType.php
- Form/Type/VichImageType.php
- Resources/doc/form/vich_file_type.md
- Resources/doc/form/vich_image_type.md
- Resources/views/Form/fields.html.twig
- Tests/Form/Type/VichFileTypeTest.php
- Tests/Form/Type/VichImageTypeTest.php
- composer.json
I take conversation from #657, I've closed PR because no more link with my fork (I think my fork was deleted at instant, it indicate ["unknow repository"](https://github.com/isaacs/github/issues/168)). No problems, I simply reopen that PR here :) @garak Sorry for response time, but I was busy. I can try to fix conflicts from this PR.
> Use asset function in form template

- Resources/views/Form/fields.html.twig
> Fix deprecation for using spaceless tag

- .travis.yml
- Command/MappingDebugCommand.php
- Command/MappingListClassesCommand.php
- Event/Event.php
- Mapping/PropertyMappingFactory.php
- Metadata/Driver/AnnotationDriver.php
- Metadata/Driver/YamlDriver.php
- Tests/EventListener/Doctrine/InjectListenerTest.php
- Tests/EventListener/Doctrine/ListenerTestCase.php
- Tests/EventListener/Doctrine/RemoveListenerTest.php
- Tests/EventListener/Propel/CleanListenerTest.php
- Tests/EventListener/Propel/InjectListenerTest.php
- Tests/EventListener/Propel/ListenerTestCase.php
- Tests/EventListener/Propel/RemoveListenerTest.php
- Tests/EventListener/Propel/UploadListenerTest.php
- Tests/Form/Type/VichImageTypeTest.php
- Tests/Handler/UploadHandlerTest.php
- Tests/Injector/FileInjectorTest.php
- Tests/Mapping/PropertyMappingFactoryTest.php
- Tests/Metadata/Driver/FileDriverTestCase.php
- Tests/Metadata/Driver/XmlDriverTest.php
- Tests/Metadata/Driver/YamlDriverTest.php
- Tests/Naming/CurrentDateTimeDirectoryNamerTest.php
- Tests/Naming/SmartUniqidNamerTest.php
- Tests/Storage/FileSystemStorageTest.php
- Tests/Storage/FlysystemStorageTest.php
- Tests/Storage/GaufretteStorageTest.php
- Tests/Storage/StorageTestCase.php
- Tests/TestCase.php
- Util/ClassUtils.php
after running phpstan on project, many errors were found.
This is an attempt to mitigate such errors (unfortunately, not to remove them completely)
> improve on static analysis

- Resources/doc/directory_namer/howto/create_a_custom_directory_namer.md
> Add a note about public directory namer requirement

- Form/Type/VichImageType.php
- Resources/doc/form/vich_image_type.md
- Tests/Form/Type/VichImageTypeTest.php
I used gnutix's PR ( #1021 ) as the base of this new one.
I have not made any changes in the logic, and I have not run automated tests. I tried it on my own project, by using the new **_storage_resolve_method_** variable, and it worked as earlier (in version 1.9).
I also extended the documentation, but it definitely needs a review.
> Diff from gnutix's PR.

- Mapping/PropertyMappingFactory.php
- Storage/AbstractStorage.php
- Storage/FileSystemStorage.php
- Storage/StorageInterface.php
- Templating/Helper/UploaderHelper.php
- Tests/Storage/FileSystemStorageTest.php
- UPGRADE.md
> allow first mapped field to be autodiscovered

- phpunit.xml.dist
Fixes #1050 
And Happy Hacktoberfest to you sir :tada:
> Remove duplicated defaults in phpunit.xml.dist

- Naming/SmartUniqueNamer.php
- Tests/Naming/SmartUniqidNamerTest.php
> Sets to lowercase, smartly handles names over 255 characters

- composer.json
- src/Templating/Helper/UploaderHelper.php
> remove Templating component from dependencies.

- src/Handler/DownloadHandler.php
- tests/Handler/DownloadHandlerTest.php
Fixes https://github.com/dustin10/VichUploaderBundle/issues/1097
> DownloadHandler: set fallback filename in download response headers

- config/mapping.xml
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/VichUploaderExtension.php
- src/Mapping/Annotation/UploadableField.php
- src/Metadata/CacheWarmer.php
- tests/Mapping/PropertyMappingFactoryTest.php
- tests/Metadata/CacheWarmerTest.php
> ✨ implement cache warmer

- src/Metadata/CacheWarmer.php
- src/Metadata/MetadataReader.php
- tests/Metadata/CacheWarmerTest.php
> 🐛 fix cache warmer when dir is empty

- docs/events/howto/remove_files_asynchronously.md
After changed the dependency in my project to `dev-master`, I found a better solution to determine the right message.
I also adapted more from the used terms in the configuration documentation.
> Improve remove files asynchronously how to

- .travis.yml
- CONTRIBUTING.md
- Makefile
- composer.json
- docker/Dockerfile73
- docker/Dockerfile74
- docker/Dockerfile80
- docs/symfony_support_policy.md
> allow php 8

- docs/storage/flysystem.md
Update "directory" param with "location" as in version 4
Update docs URL.
> Update OneupFlysystemBundle docs

- src/Naming/SmartUniqueNamer.php
- tests/Naming/SmartUniqidNamerTest.php
> SmartUniqueNamer fix bug with dot in filename

- UPGRADE.md
- composer.json
- docs/index.md
> Make symfony/form a suggestion

- docs/usage.md
- src/Mapping/Annotation/Uploadable.php
- src/Mapping/Annotation/UploadableField.php
> Allow PHP8 Attribute

- composer.json
- src/Metadata/Driver/AbstractYamlDriver.php
- src/Metadata/Driver/XmlDriver.php
Refs https://github.com/dustin10/VichUploaderBundle/pull/960#discussion_r652571339 (updated as ^2.0 is now ^2.4)
> Re-allow jms/metadata v1

- src/Mapping/Annotation/UploadableField.php
Refs https://github.com/dustin10/VichUploaderBundle/pull/1210#discussion_r652751649
> Delete wrong copy-paste

- config/mapping.xml
- docs/configuration_reference.md
- docs/usage.md
- phpstan-baseline.neon
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/VichUploaderExtension.php
- src/Mapping/Annotation/Uploadable.php
- src/Mapping/Annotation/UploadableField.php
- src/Mapping/AnnotationInterface.php
- src/Metadata/Driver/AnnotationDriver.php
- src/Metadata/Driver/AttributeReader.php
- tests/DependencyInjection/VichUploaderExtensionTest.php
- tests/DummyAttributeEntity.php
- tests/Metadata/Driver/AttributeReaderTest.php
> Php8 attributes fix

- src/Mapping/Annotation/Uploadable.php
- src/Mapping/Annotation/UploadableField.php
> remove "internal" from atttribute definition

- src/Entity/File.php
- Implement `getWidth()` and `getHeight()`, which respectively return image width and height ;
- Implement `getHtmlDimensions()` which returns HTML formatted dimensions.
Closes #1255
> Add dimensions helper functions to File class

- phpstan-baseline.neon
- src/EventListener/Doctrine/BaseListener.php
- src/EventListener/Doctrine/CleanListener.php
- src/Handler/UploadHandler.php
- src/Storage/AbstractStorage.php
- src/Storage/StorageInterface.php
- tests/EventListener/Doctrine/CleanListenerTest.php
- tests/EventListener/Doctrine/ListenerTestCase.php
- tests/Handler/UploadHandlerTest.php
This should fix #1252 by restoring the same behaviour we had in branch 1.18
> revert changes to clean files

- src/Form/Type/VichFileType.php
- src/Form/Type/VichImageType.php
- tests/Fixtures/App/app/config/routing.yml
- tests/Fixtures/App/templates/default/edit_with_property_path.html.twig
- tests/Fixtures/App/templates/default/upload_with_property_path.html.twig
- tests/Fixtures/TestBundle/src/Controller/DefaultController.php
- tests/Form/Type/VichFileTypeTest.php
- tests/Form/Type/VichImageTypeTest.php
- tests/Functional/UploadTest.php
Fixes https://github.com/dustin10/VichUploaderBundle/issues/1273
Closes https://github.com/dustin10/VichUploaderBundle/pull/1283
> Allow the use of propertyPath

- .github/workflows/build.yaml
> Allow symfony/flex composer plugin

- src/Templating/Helper/UploaderHelper.php
- src/Twig/Extension/UploaderExtension.php
> Don't pass deprecated $className

- src/Command/MappingDebugCommand.php
- tests/Command/MappingDebugCommandTest.php
> Add command completion for vich:mapping:debug

- src/Command/MappingDebugClassCommand.php
- templates/Collector/mapping_collector.html.twig
> Improve output of vich:mapping:debug-class

- CONTRIBUTING.md
- Makefile
- docker/Dockerfile81
- docs/configuration_reference.md
- docs/directory_namer/howto/create_a_custom_directory_namer.md
- docs/events/howto/remove_files_asynchronously.md
- docs/file_namer/howto/create_a_custom_file_namer.md
- docs/known_issues.md
- docs/mapping/xml.md
- docs/mapping/yaml.md
- docs/namers.md
- docs/storage/flysystem.md
- docs/storage/gaufrette.md
- docs/usage.md
- src/Mapping/PropertyMappingFactory.php
- templates/Collector/mapping_collector.html.twig
- tests/Fixtures/App/app/config/config.yml
* improving use on PHP8
* improving docs to be more PHP8-friendly
* making docs more consistent with default recipe
* add a testing image for 8.1
> improve support for php 8

- docs/storage/flysystem.md
> fix(doc): Wrong oneup service name

- config/mapping.xml
- src/DependencyInjection/Compiler/RegisterMappingDriversPass.php
- src/Metadata/Driver/AnnotationDriver.php
- tests/Metadata/Driver/AnnotationDriverTest.php
> Make AnnotationDriver compatible with all supported adapters

- composer.json
> Allow v5.4 of Symfony string

- src/Twig/Extension/UploaderExtension.php
- src/Twig/Extension/UploaderExtensionRuntime.php
- tests/Twig/Extension/UploaderExtensionTest.php
> make Twig extension lazy

- .github/workflows/build.yaml
- config/twig.xml
- docs/usage.md
- phpstan-baseline.neon
- tests/Fixtures/App/templates/default/edit.html.twig
- tests/Fixtures/TestBundle/src/Controller/DefaultController.php
- tests/Functional/UploadTest.php
- tests/Functional/WebTestCase.php
- tests/Twig/Extension/UploaderExtensionTest.php
> fix Twig extension

- config/twig.xml
- src/Twig/Extension/UploaderExtension.php
- src/Twig/Extension/UploaderExtensionRuntime.php
- tests/Twig/Extension/UploaderExtensionTest.php
> backport Twig extension enhancement to 1.x

- composer.json
- phpunit.xml.dist
- tests/Form/Type/VichFileTypeTest.php
- tests/Form/Type/VichImageTypeTest.php
- tests/Functional/UploadTest.php
- tests/Handler/DownloadHandlerTest.php
- tests/Handler/UploadHandlerTest.php
- tests/Mapping/PropertyMappingFactoryTest.php
- tests/Mapping/PropertyMappingTest.php
- tests/Metadata/Driver/AnnotationDriverTest.php
- tests/Metadata/Driver/FileDriverTestCase.php
- tests/Metadata/Driver/XmlDriverTest.php
- tests/Metadata/Driver/YamlDriverTest.php
- tests/Metadata/MetadataReaderTest.php
- tests/Naming/Base64NamerTest.php
- tests/Naming/CurrentDateTimeDirectoryNamerTest.php
- tests/Naming/HashNamerTest.php
- tests/Naming/OrignameNamerTest.php
- tests/Naming/PropertyDirectoryNamerTest.php
- tests/Naming/PropertyNamerTest.php
- tests/Naming/SlugNamerTest.php
- tests/Naming/SmartUniqidNamerTest.php
- tests/Naming/SubdirDirectoryNamerTest.php
- tests/Naming/UniqidNamerTest.php
- tests/Storage/FileSystemStorageTest.php
- tests/Storage/Flysystem/AbstractFlysystemStorageTest.php
- tests/Storage/GaufretteStorageTest.php
- tests/Storage/StorageTestCase.php
> prepare tests for PHPUnit 10

- composer.json
- src/Metadata/CacheWarmer.php
> fix deprecation

- src/Exception/MissingPackageException.php
- src/Form/Type/VichFileType.php
- src/Form/Type/VichImageType.php
- src/Handler/DownloadHandler.php
- src/Metadata/CacheWarmer.php
- src/Metadata/Driver/AbstractYamlDriver.php
- src/Metadata/Driver/XmlDriver.php
Fixes a deprecation warning in preparation for PHP 8.4.
> Use explicit nullables types

- src/Naming/Polyfill/FileExtensionTrait.php
- tests/Naming/SmartUniqidNamerTest.php
As suggested in https://github.com/dustin10/VichUploaderBundle/pull/1484#issuecomment-2560169689
> 🎨 add gpx to extension map

- .php-cs-fixer.php
- tests/Command/MappingDebugClassCommandTest.php
- tests/Command/MappingDebugCommandTest.php
- tests/DependencyInjection/VichUploaderExtensionTest.php
- tests/Form/Type/VichFileTypeTest.php
- tests/Form/Type/VichImageTypeTest.php
- tests/Functional/UploadTest.php
- tests/Handler/DownloadHandlerTest.php
- tests/Handler/UploadHandlerTest.php
- tests/Mapping/PropertyMappingFactoryTest.php
- tests/Mapping/PropertyMappingTest.php
- tests/Metadata/Driver/AnnotationDriverTest.php
- tests/Metadata/Driver/FileDriverTestCase.php
- tests/Metadata/MetadataReaderTest.php
- tests/Naming/Base64NamerTest.php
- tests/Naming/CurrentDateTimeDirectoryNamerTest.php
- tests/Naming/HashNamerTest.php
- tests/Naming/OrignameNamerTest.php
- tests/Naming/PropertyDirectoryNamerTest.php
- tests/Naming/PropertyNamerTest.php
- tests/Naming/SlugNamerTest.php
- tests/Naming/SmartUniqidNamerTest.php
- tests/Naming/SubdirDirectoryNamerTest.php
- tests/Naming/UniqidNamerTest.php
- tests/Storage/FileSystemStorageTest.php
- tests/Storage/Flysystem/AbstractFlysystemStorageTestCase.php
- tests/Storage/Flysystem/MountManagerFlysystemStorageTest.php
- tests/Storage/GaufretteStorageTest.php
- tests/Storage/StorageTestCase.php
- tests/Templating/Helper/UploadHelperTest.php
> migrate to phpunit attributes

- src/Command/MappingDebugClassCommand.php
- src/Command/MappingDebugCommand.php
- src/Command/MappingListClassesCommand.php
> use attributes in commands

- src/Naming/ConfigurableDirectoryNamer.php
- tests/DependencyInjection/VichUploaderExtensionTest.php
> fix argument type

- src/Command/MappingDebugClassCommand.php
- src/Command/MappingDebugCommand.php
- src/Command/MappingListClassesCommand.php
> Add description within the command attribute.

- UPGRADE.md
- src/Naming/Polyfill/FileExtensionTrait.php
- tests/Naming/SmartUniqidNamerTest.php
> keep xlsb extension

- UPGRADE.md
- config/factory.xml
- config/namer.xml
- docs/directory_namer/howto/create_a_custom_directory_namer.md
- docs/file_namer/howto/create_a_custom_file_namer.md
- docs/namers.md
- src/DependencyInjection/VichUploaderExtension.php
- src/Mapping/PropertyMappingResolver.php
- tests/Fixtures/App/app/config/config.yml
- tests/Fixtures/TestBundle/src/Resources/config/doctrine/Image.orm.xml
- tests/Mapping/PropertyMappingFactoryTest.php
> do not inject container in PropertyMappingResolver
