Resources/doc/usage.md

The `@note` annotation thrown exception `Doctrine\Common\Annotations\AnnotationException`:
```
[Semantical Error] The annotation "@note" in property Acme\DemoBundle\Entity\Image::$imageFile was never imported. Did you maybe forget to add a "use" statement for this annotation?
```

Fix error with annotation using Doctrine ORM

---

Resources/doc/form/vich_file_type.md
Resources/doc/form/vich_image_type.md

The `twig.form.resources` Twig config key is deprecated.

Replace form.resources with form_themes key

---

.travis.yml

The symfony 2.4 version which is no longer supported.
[Symfony Version Checker](http://symfony.com/roadmap?version=2.4#checker)
PS- BTW, version 2.5 support ends by July 2015 (next month).

Removed test target for symfony 2.4

---

.gitignore
CONTRIBUTING.md
composer.json
runTests.sh

I've created this small bash script when I was developing the unit test for #405 to help me run the tests against all the Symfony versions supported by the bundle.
I've made a few adjustments today and decided to add it to my fork.
I'm creating this PR in case you're interested in adding it to the bundle.
It supports passing a single SF2 version and/or the arguments for phpunit. Example:
```
~$ SYMFONY_VERSION=2.7.1 ./runTests.sh --filter testCustomFileNameProperty
```
PS- I've only tested this in Ubuntu 14.04 with the packaged PHP version (5.5.9).

Created helpful bash script for running tests locally.

---

Resources/doc/known_issues.md
Resources/doc/usage.md

I think for simlicity we could avoid element names. The element name in `@var` is optional and not required. If anybody copy/paste this code from examples he most probably change the names so he should change it in few places (in code and annotation).

Remove element names in @var annotation and use namespace

---

Resources/doc/usage.md

The `name` could override `doctrine.orm.naming_strategy`.
Other developers could use different naming strategy so would be better to avoid it in example in favor to easy copy/paste.

Remove name parameter from field mapping

---

Resources/doc/known_issues.md
Resources/doc/usage.md

I think better to make properties `private` and use other modifiers only if you need.
Another one improvement for convenient copy/paste.

Make properties as private in docs examples

---

EventListener/Doctrine/UploadListener.php

In an entity with multiple uploadable fields, is there a reason to compute the change set before all fields have been updated?

Compute change set after updating all fields

---

Handler/DownloadHandler.php

The result of stream_copy_to_stream is the number of byte copied and shouldn't be echoed.

Fix DownloadHandler

---

composer.json

It removes 3 files from autoloading, not much, but a good start to clean up the optimized autoloader maps.
A lot of test files remains in the loader path because the root directory is the autoloading psr-4 root directory too. It should be separated to another dir.

remove test namespace from autoloading

---

Resources/doc/generating_urls.md

Otherwise, twig just crunches it all together, eg `FooBundleEntityProduct`, and throws a `Class not found` Reflection Exception.

Use double slashes in twig example

---

Resources/views/Form/fields.html.twig

Before this change, an invalid image/file field was missing the `has-error` class, resulting in missing red coloring of label and error
before:
after:

Force 'has-error' when invalid

---

Resources/config/mapping.xml

Hey!
Since I'm currently playing with this bundle, I submit a bugfix about metadata changes detection. Basically, the JMS metadata factory was always in no debug mode meaning once the metadata were loaded, no more checks were done on them.
This PR fixes it by propagating the `kernel.debug` flag into the metadata factory and then, bring back the metadata changes detection :)

Fix metadata changes detection

---

DependencyInjection/Configuration.php
DependencyInjection/VichUploaderExtension.php
Resources/doc/index.md
Resources/doc/storage/custom.md
Tests/DependencyInjection/VichUploaderExtensionTest.php

This PR fixes #573 by allowing to define a custom storage service name in the configuration. 
To to not break the BC, I have chosen to prefix the service name with an `@` in order to inform the DI extension we are using a custom storage service. I think the `@` char is the best option since it is also used in yaml service definition :)
WDYT?

Add custom storage support

---

composer.json

Hey!
This PR refines the composer dependencies in order to be able to run phpunit tests locally just after running a `composer install` (a bunch of dependencies were missing if we use Symfony 3).
It also refines dependencies in order to make tests green even if we install with the lowest deps: `composer install --prefer-lowest --prefer-stable`.
Since travis is ran with the full `symfony/symfony`, this has not been detected previously.

[Composer] Refine dependencies

---

Util/Transliterator.php

Here is safer way to check if we can use ICU related function.
In some case and some environnement I get a warning like this one: 
```
Warning: transliterator_transliterate(): Could not create transliterator with
ID "Any-Latin; Latin-ASCII; [\u0100-\u7fff] remove"
(transliterator_create: unable to open ICU transliterator
with id "Any-Latin; Latin-ASCII; [\u0100-\u7fff] remove": U_INVALID_ID)
```
By the way, this should fix #554

Avoid some warning with Transliterator

---

Event/Event.php
Handler/AbstractHandler.php
Handler/UploadHandler.php
Injector/FileInjector.php
Mapping/PropertyMapping.php
Mapping/PropertyMappingFactory.php
Resources/doc/mapping/xml.md
Storage/AbstractStorage.php
Storage/FlysystemStorage.php
Storage/GaufretteStorage.php
Templating/Helper/UploaderHelper.php
Tests/EventListener/Doctrine/ListenerTestCase.php
Tests/EventListener/Doctrine/RemoveListenerTest.php
Tests/EventListener/Propel/ListenerTestCase.php
Tests/Handler/DownloadHandlerTest.php
Tests/Handler/UploadHandlerTest.php
Tests/Mapping/PropertyMappingFactoryTest.php
Tests/Metadata/Driver/FileLocatorTest.php
Tests/Naming/PropertyNamerTest.php
Tests/Storage/FlysystemStorageTest.php
Tests/Storage/GaufretteStorageTest.php
Tests/Storage/StorageTestCase.php
Util/ClassUtils.php

It might be cool to simplify all class imports.
I noticed there was a bug in some phpdoc in v0.14.0 because my IDE wasn't auto-completing correctly.

[Code style] Import all FQCNs when possible

---

DependencyInjection/Compiler/RegisterPropelModelsPass.php

The Compiler pass registers listeners when the mapping used by the class is a Propel mapping.
But if there is no such mapping, there is no need to load the metadata at all.
The loading of metadata relies on an unsupported usage of Symfony (getting a service instance during the container building phase), and that it breaks in Symfony 3.2 (one of the dependencies of the ``vich_uploader.metadata_reader`` service depends on a cache pool on 3.2, which is not yet ready to be instantiated at the time your compiler pass runs).
Thanks to this change, the broken behavior only happens for people using the Propel integration (next plan is to look for a way to achieve the necessary behavior without instantiating the service here, to solve it for them). anyone not using the Propel 1 integration would …

Avoid loading all metadata when there is no propel mapping

---

Resources/config/gaufrette.xml

Fixed `ServiceCircularReferenceException` for service `vich_uploader.storage`

Gaufrette circular reference

---

Form/Type/VichFileType.php
Resources/config/form.xml

Translator is injected in form type service. I think it's not necessary because label form is translate and we can set custom translation domains.
More, It causes bug with symfony profiler who detects the string translate as an ID from domain "messages" in AppBundle.

No need translator injection in form type

---

VichUploaderBundle.php

The changeset was necessary after a change in symfony master.
The service 'cache.annotations', which is resolved when the metadata
reader is received from the container in the Pass, is not available
at that point in the container compilation process.
This changeset defers the PropelModelsPass until a point in time, where the
container is fully accessible.
Ref: symfony/symfony#19205

Defer RegisterPropelModelsPass

---

Entity/File.php
Metadata/Driver/AnnotationDriver.php
Resources/doc/usage.md

Another one small step to reduce boilerplate when using the bundle.
TODO:

Create embeddable entity for storing common file information

---

Handler/UploadHandler.php
Mapping/PropertyMapping.php
Tests/Handler/UploadHandlerTest.php
Tests/Mapping/PropertyMappingTest.php
Tests/TestCase.php

Remove values for each file-related property on remove

---

EventListener/Doctrine/BaseListener.php
EventListener/Propel/BaseListener.php
Metadata/MetadataReader.php
Tests/DependencyInjection/VichUploaderExtensionTest.php
Tests/Metadata/MetadataReaderTest.php

try cover #692 with test and implements support of the second argument for `getUploadableFields` (it called with 2 arguments in some places)

Added test for #692 and fix some method

---

composer.json

see
https://github.com/symfony/symfony/pull/20097
https://github.com/symfony/recipes-contrib/pull/22#issuecomment-301831276

Add doctrine/annotations dependency

---

Tests/Handler/DownloadHandlerTest.php
Util/Transliterator.php

I have a problem with the character º in a filename. Does not pass symfony validations to accept only ascii characters
Symfony make this validation for non ascii characters for filename. See the code [here](https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/HttpFoundation/ResponseHeaderBag.php#L287)
So, I added a replace with the same regex in the funcion Vich\UploaderBundle\Util\Transliterator::transliterate

Added symfony validation for non ascii characters

---

.travis.yml
DependencyInjection/Configuration.php
DependencyInjection/VichUploaderExtension.php
Form/Type/VichFileType.php
Form/Type/VichImageType.php
Handler/DownloadHandler.php
Mapping/PropertyMapping.php
Resources/config/form.xml
Resources/doc/downloads/serving_files_with_a_controller.md
Resources/doc/form/vich_file_type.md
Resources/doc/form/vich_image_type.md
Resources/views/Form/fields.html.twig
Storage/StorageInterface.php
Templating/Helper/UploaderHelper.php
Tests/Fixtures/App/src/TestBundle/Entity/Product.php
Tests/Handler/DownloadHandlerTest.php
Tests/Vich/UploaderBundle/Tests/Form/Type/VichFileTypeTest.php
Tests/Vich/UploaderBundle/Tests/Form/Type/VichImageTypeTest.php
Twig/Extension/UploaderExtension.php
UPGRADE.md
composer.json

Notable changes:
- form theme is automatically registered now - no config changes required (DX, also needed for https://github.com/symfony/recipes-contrib/pull/22 )
- `VichFileType`: `download_link` deprecated with `download_uri`, which supports callable
- `VichFileType`: `download_label` now supports `true` (use original file name), `callable` and instances of `PropertyPath`
- `VichFileType`: unified `translation_domain` option usage
- `VichImageType`: added option `image_uri`
- `VichImageType`: added optional integration with LiipImagineBundle
- download handler now supports `true` (use original file name) as served file name
- fixed phpdocs for `StorageInterface`, `UploaderHelper`, `DownloadHandler`
- reorganized test suite: validate docs separately from unit tests

Rework form options, download handler options

---

Resources/config/form.xml

The `form.property_accessor` service is a dependency since 1.6.0. This requires symfony's form component to be enabled or other measures from the user if that was not the case. This service happens to be an alias for the more common `property_accessor`.
While I can come up with a reason to use `form.property_accessor`, using this service is more likely to break applications then while using `property_accessor`, like in my case, where I'm building an API and thus don't need the form component to be enabled in the framework, where `form.property_accessor` is part of.
So while this still is not bc proof, this pr could mitigate the problem a bit.

New service requirement breaks bc

---

DependencyInjection/Configuration.php
DependencyInjection/VichUploaderExtension.php
Resources/doc/configuration_reference.md
composer.json

This makes loading of form and templating services optional, like it's already optional to load twig stuff.
This helps minimize APIs, and also offers a ways to work around requiring `form.property_access`, that is a dependency of this bundle since 1.6.0.

Add options to not load form and templating services

---

Adapter/PHPCR/PHPCRAdapter.php
Tests/Adapter/PHPCR/PHPCRAdapterTest.php
Tests/Fixtures/App/app/config/routing.yml

see https://travis-ci.org/dustin10/VichUploaderBundle/jobs/243216587
1. `getEntity` is deprecated, use `getObject` insetad.
2. `_method` requirements is deprecated, use `methods` option instead

Stop using deprecated code

---

Resources/doc/mapping/yaml.md

Added some additional information on how the YAML entity files should be names, as it must correspond with the namespace_prefix setting in order for the file to be found correctly.

Document naming convention for .yml config files

---

DependencyInjection/VichUploaderExtension.php

This completes 49a32616471ade5eab0c3e50960153a0491662e9 fixing another usage of the deprecated `DefinitionDecorator`.

Fixed more usages of DefinitionDecorator

---

Naming/Base64Namer.php
Resources/config/namer.xml
Resources/doc/namers.md
Tests/Naming/Base64NamerTest.php

I wanted a namer in my application which creates shorter IDs similar to YouTube video IDs. I hope it can be useful to others.
The implementation is based on HashNamer, but since this bundle is targeting PHP7, I used the random_int() function instead. The name is URL-safe and has configurable length.

Base64Namer

---

Entity/File.php
Mapping/Annotation/UploadableField.php
Mapping/PropertyMapping.php
Metadata/Driver/AnnotationDriver.php
Metadata/Driver/XmlDriver.php
Metadata/Driver/YamlDriver.php
Resources/doc/mapping/xml.md
Resources/doc/mapping/yaml.md
Resources/doc/usage.md
Storage/AbstractStorage.php
Tests/Metadata/Driver/AnnotationDriverTest.php
Tests/Metadata/Driver/FileDriverTestCase.php

support for missing `dimensions` property for `image/*` types.

add `dimensions` property for image/* types

---

Naming/Base64Namer.php
Naming/HashNamer.php
Tests/Naming/Base64NamerTest.php
Tests/Naming/HashNamerTest.php

It appears that files namers are currently determining file extension in different ways.
This PR unifies it by using `Polyfill\FileExtensionTrait` in all file namers.

Uses FileExtensionTrait in all files namers.

---

.travis.yml
composer.json
runTests.sh

Actually, you cannot do a composer install nor run the tests because of 2 things:
1 - php7.1 is now the minimum and doctrine/mongodb-odm needs ext-mongo which doesn't exist for php7.1 so you need to do this: http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/introduction.html#using-php-7
2 - you can't run the script runTests.sh because it tries to test SF 2.8 and 3.3 which is not possible anymore with the new requirements
Edit: travis failing because ext-mongodb is missing (which should be used with php7.1)

Fix test environment for the new environment requirement

---

Resources/config/factory.xml
Resources/config/form.xml
Resources/config/handler.xml
Resources/config/storage.xml
Resources/config/templating.xml

I extended the VichImageType class and I had to put aliases on 3 services to be able to use the autowiring.
Maybe we could also add alias for PropertyAccessorInterface and CacheManager too.

Add aliases to be able to extend VichImageType

---

Form/Type/VichImageType.php
Tests/Form/Type/VichImageTypeTest.php

`Liip\ImagineBundle\Imagine\Cache\CacheManager::getBrowserPath` should receive a relative path in the first argument but not an URI.
Moreover this works if `LiipImagineBundle` and `VichUploaderBundle` properly configured, config options `vich_uploader.mappings.default.upload_destination` and `liip_imagine.loaders.default.filesystem.data_root` must point to the same directory.
Current version might only work if URI that returned by the Storage equals to relative path for Imagine.

Fix `imagine_pattern` option behavior in VichImageType

---

Form/Type/VichFileType.php

When using NelmioApiDocBundle, the forms parent is null.
For this reason, it is necessary tocheck if it is null before getting its data

Check if parent is null

---

Resources/config/namer.xml

In API we don't use form component at all so it's disabled completely but bundle tries to inject it's property accessor and fails. PropertyDirectoryNamer constructors allows to pass null so this works

If form component is disabled then inject null instead of form's property accessor

---

runTests.sh

Hi there,
running the `./runTests.sh` on a machine where the php.ini has a different timezone set than UTC, for example 'America/Los_Angeles', fails some phpunit tests.
How about we set the timezone to default UTC for running the testsuite?
Cheers,
Kim

use default timezone UTC for phpunit tests

---

Handler/DownloadHandler.php
Tests/Handler/DownloadHandlerTest.php

Fix: #774 and also covers #923 
|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | no
| BC Break    | no
Fixes null file and exception thrown during `$mapping->getFile($object)` for mimeType

Fix #774 and covers #923

---

Resources/views/Form/fields.html.twig

This allows the whitespace removal to be done at compile time, rather than runtime (thus improving performance).
Additionally, this will be more compatible, as the spaceless filter does not exist until Twig 2.7 (and composer.json does not declaring any particular version of Twig as a requirement).
This is a strict improvement to #968.

Use whitespace control tags instead of spaceless

---

Storage/FlysystemStorage.php

According to the official documentation : « If you do not specify the 'b' flag when working with binary files, you may experience strange problems with your data, including broken image files and strange problems with \r\n characters. »

Change file open mode

---

Naming/SmartUniqueNamer.php
Resources/config/namer.xml
Resources/doc/namers.md
Tests/Naming/SmartUniqidNamerTest.php

Currently, this bundle has a namer for uniqueness that is too harsh (using simply uniqid) and a namer that tries to keep original name, that is too dumb (not transforming name and prepending uniqid).
This namer tries to get the best of both worlds, so it's named "smart" 😎

add SmartUniqueNamer

---

Util/ClassUtils.php

Trying to read metadata on a referenced document class (proxy) results in a critical exception.
Since Doctrine\Common\Util\ClassUtils is considered as deprecated:
https://github.com/doctrine/common/issues/867
I suggest this implementation:
https://github.com/api-platform/core/blob/master/src/Util/ClassInfoTrait.php#L38

Compatibility with doctrine/mongodb-odm v.2.0; Drop DoctrineClassUtils;

---

Naming/Polyfill/FileExtensionTrait.php
Naming/UniqidNamer.php
Tests/Naming/UniqidNamerTest.php

Files with an extension ".0" typically occur as output of file split
operations and compression utilities. Although unusual, such extensions
are valid and should be processable by VichUploader.
Fixes #1030

Fix naming files with ".0" extension

---

src/DataCollector/MappingCollector.php

Fixes #1061 
```
PHP Fatal error:  Declaration of Vich\UploaderBundle\DataCollector\MappingCollector::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Exception $exception = NULL): void must be compatible with Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Throwable $exception = NULL)
```

fix: MappingCollector::collect declaration

---

src/Storage/FlysystemStorage.php
tests/Storage/Flysystem/AbstractFlysystemStorageTest.php
tests/Storage/Flysystem/MountManagerFlysystemStorageTest.php
tests/Storage/Flysystem/PsrContainerFlysystemStorageTest.php

I am currently working on integrating the official Flysystem bundle (https://github.com/thephpleague/flysystem-bundle) into this one and I realized there is a huge downside in the current implementation: the MountManager provided by OneUpFlysystemBundle is public and references *directly* all the filesystems defined with the bundle. This means that 1/ the container can't be optimized to remove unused filesystems from the compiled code and 2/ each time the MountManager service is instanciated, all the filesystem services are instanciated as well at the same time, even if they are not useful in the context. This hurts performance and can lead to unstable application if a storage tries to connect to a service which is down or inaccessible.
This PR adds support for a PSR ContainerInterface …

Add support for a ContainerInterface instance in FlysystemStorage

---

composer.json
config/flysystem.xml
docs/storage/flysystem.md
src/DependencyInjection/Compiler/RegisterFlysystemRegistryPass.php
src/Exception/MissingPackageException.php
src/VichUploaderBundle.php
tests/Kernel/AppKernelTrait.php
tests/Kernel/FilesystemAppKernel.php
tests/Kernel/FlysystemOfficialAppKernel.php
tests/Kernel/FlysystemOneUpAppKernel.php
tests/Kernel/SimpleAppKernel.php
tests/Storage/Flysystem/PsrContainerFlysystemStorageTest.php
tests/VichUploaderBundleTest.php

Based on https://github.com/dustin10/VichUploaderBundle/pull/1082
Fix https://github.com/dustin10/VichUploaderBundle/issues/1015
This PR implements support for the official Flysystem bundle (https://github.com/thephpleague/flysystem-bundle). It keeps backward compatibility with OneupFlysystemBundle while adding the possibility to wire a League FilesystemBundle storage too.
This PR also adds several tests to ensure the bundle boots using various configuration options and to ensure that I did not break the OneupFlysystemBundle usage.

Implement support for the official Flysystem bundle and adapt documentation

---

tests/Form/Type/VichFileTypeTest.php
tests/Handler/UploadHandlerTest.php

The following warnings were raised each time I ran the tests using PHPUnit 8:
```
There were 7 warnings:
1) Vich\UploaderBundle\Tests\Form\Type\VichFileTypeTest::testConfigureOptionsBC with data set #0 (array(true), array(true))
assertArraySubset() is deprecated and will be removed in PHPUnit 9.
2) Vich\UploaderBundle\Tests\Form\Type\VichFileTypeTest::testConfigureOptionsBC with data set #1 (array(false), array(false))
assertArraySubset() is deprecated and will be removed in PHPUnit 9.
3) Vich\UploaderBundle\Tests\Form\Type\VichFileTypeTest::testEmptyDownloadLinkDoNotThrowsDeprecation
assertArraySubset() is deprecated and will be removed in PHPUnit 9.
4) Vich\UploaderBundle\Tests\Form\Type\VichImageTypeTest::testConfigureOptionsBC with data set #0 (array(true), array(true)) …
```

Fix PHPUnit 8 warnings

---

src/DependencyInjection/Compiler/RegisterFlysystemRegistryPass.php

Fix https://github.com/dustin10/VichUploaderBundle/issues/1091
This allows back manual wiring of a Flysystem service in case no bundle is used.

Fix Flysystem manual wiring BC break

---

docs/usage.md

I don't know if it's the auto-validation added since symfony4.3 that does that. 
but if I don't add the ? in the annotation: 
@var File   ->  @var ?File
I have a notnull constraint that prevents the normal behaviour of the form even if it is configured with required=false
When I edit an uploadable without wanting to change the image, the validator blocks on "imageFile can't be null".

Avoid the creation of a notnull constraint

---

src/Storage/AbstractStorage.php

I had to implement a custom [`MimeTypeGuesserInterface`](https://symfony.com/doc/current/components/mime.html#adding-a-mime-type-guesser), which is quite costly to run.
This simple fix removes some redundant calls to File::getMimeType().
_Context_
_I need to handle SVG images, for which PHP's MIME detection is [somewhat bogus](https://bugs.php.net/bug.php?id=79045)_
_I will gladly share my implementation of `MimeTypeGuesserInterface` on demand. I was also able to extract [dimensions](https://github.com/dustin10/VichUploaderBundle/blob/master/src/Storage/AbstractStorage.php#L44) from the `width` and `height` SVG attributes. I would submit another PR if you are interested._

Reduce number of calls to File::getMimeType() during upload.

---

src/Exception/MappingNotFoundException.php
src/Exception/MissingPackageException.php
src/Exception/NameGenerationException.php
src/Exception/NoFileFoundException.php
src/Exception/NotUploadableException.php
src/Exception/VichUploaderExceptionInterface.php

@garak This interface will allow to catch all the specific VichUploader exception without the other Runtime exception.

Add VichUploaderExceptionInterface

---

src/Naming/SmartUniqueNamer.php
tests/Naming/SmartUniqidNamerTest.php

I replaced 
line: $originalBasename = \basename($originalName, '.' .$originalExtension);
with: $originalBasename = pathinfo($originalName, PATHINFO_FILENAME);
all tests are passed

fix to problem with uppercase extension, issue #1125

---

.travis.yml
composer.json
src/DependencyInjection/Configuration.php
tests/DependencyInjection/VichUploaderExtensionTest.php
tests/Fixtures/App/app/config/config.yml
tests/Handler/UploadHandlerTest.php
tests/Kernel/FilesystemAppKernel.php
tests/Kernel/FlysystemOfficialAppKernel.php
tests/Kernel/FlysystemOneUpAppKernel.php
tests/Kernel/SimpleAppKernel.php

The signature of method `NodeDefinition::setDeprecated()` has been updated to `NodeDefinition::setDeprecation(string $package, string $version, string $message)`.
See https://github.com/symfony/symfony/blob/5.1/UPGRADE-5.1.md

Deprecation since Symfony 5.1: NodeDefinition::setDeprecated() requires 3 arguments

---

docs/form/vich_file_type.md
docs/form/vich_image_type.md

Added the missing "delete_label" option to the docs.
Without this, "vich_uploader.form_label.delete_confirm" is shown (which also shows here an issue of translation)

Added "delete_label" option to the documentation

---

docs/events/events.md
docs/events/howto/remove_files_asynchronously.md
docs/index.md
src/Event/Event.php
src/Handler/UploadHandler.php
tests/Handler/UploadHandlerTest.php

This pull request, adds the possibility to cancel events. This has the advantage to cancel the actual remove request and dispatch a message to make the file removal asynchronously.
Cancellation only works for the `pre_remove` event.
Fixes #1155

Add cancellability for pre events

---

src/Storage/GaufretteStorage.php

Should resolve issue when uploading file with AzureBlobStorage adpater.
Error message displayed: 
`Failed to set metadata for blob "$path" in container "$container": The specified container does not exist. (ContainerNotFound).`
Resolves issue #708

Fix for uploading file on Azure Blob

---

templates/Form/fields.html.twig

I found that, when using Symfony Bootstrap 4 theme, VichUploaderBundle widgets are not rendered with proper `is-invalid` class.
This PR forces such class in case of error.

add missing error class

---

templates/Collector/mapping_collector.html.twig

This tiny change fixes the padding and style in the debug toolbar.
Before:
After:
This is because profiler styles are explicitly looking for `<b>` there and not `<strong>`: https://github.com/symfony/web-profiler-bundle/blob/95fb24b09551688a09cffac95a2ddbb907833f07/Resources/views/Profiler/toolbar.css.twig#L177

Fix Collector toolbar spacing

---

src/Mapping/Annotation/UploadableField.php

Mapping dimensions should be a string containing the property name to map and not an array.

Converted dimensions mapping type from array to string

---

phpstan-baseline.neon
src/Form/DataTransformer/FileTransformer.php

This will fix the following deprecation:
>method "Symfony\Component\Form\DataTransformerInterface::reverseTransform()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Vich\UploaderBundle\Form\DataTransformer\FileTransformer" now to avoid errors or add an explicit @return annotation to suppress this message.

fix Symfony 5.4 deprecation

---

config/doctrine/File.orm.xml
src/Entity/File.php
src/Resources/config/doctrine/File.orm.xml

Different approach to #1243, change the configuration to XML (as suggested in https://symfony.com/doc/current/bundles/best_practices.html#doctrine-entities-documents).
Symlink in `src/Resources/config/doctrine` is needed for backwards compatibility, as the bundle path detection is fixed in Symfony 5.4.

Rework Doctrine mapping to XML to fix issue with SF 5.4

---

src/Entity/File.php

Add missing quotes to `getHtmlDimensions`, around **width** and **height** values.
Resolves: https://github.com/dustin10/VichUploaderBundle/pull/1256#discussion_r781181899

Add missing quotes to getHtmlDimensions

---

src/VichUploaderBundle.php

As per the discussion in #1214 with @garak, the `@internal` annotation on `Vich\UploaderBundle\VichUploaderBundle` causes a strike-through to appear in the class name in `config/bundles.php` within PhpStorm and possibly other IDEs.
This makes it look like the developer has done something wrong.
This PR simply removes the annotation from this class.

Remove internal annotation from bundle class

---

src/EventListener/Doctrine/RemoveListener.php
tests/EventListener/Doctrine/RemoveListenerTest.php

fixes #1266

---

src/Templating/Helper/UploaderHelper.php
src/Templating/Helper/UploaderHelperInterface.php
src/Twig/Extension/UploaderExtension.php
tests/Functional/WebTestCase.php
tests/Templating/Helper/UploadHelperTest.php
tests/Twig/Extension/UploaderExtensionTest.php

Hi @garak. 
I recently tried the 1.19 version and got an issue.
Since the UploaderHelper is/will be final, I cannot extends it.
But since this class is required (and not an interface) in the construct of the UploaderExtension, I cannot use decoration either.
This PR solve this issue.

Allow to decorate the UploaderHelper

---

docs/storage/flysystem.md

Otherwise you`ll see an error: Service \"product_image_fs\" not found: the container inside \"Symfony\\Component\\DependencyInjection\\Argument\\ServiceLocator\" is a smaller service locator that only knows about the \"oneup_flysystem.product_image_fs_filesystem\" service."
oneup/flysystem-bundle versions : * 4.0.7

Fix documentation for integration with oneup/flysystem-bundle

---

composer.json
config/mapping.xml
docs/commands.md
src/Command/MappingDebugClassCommand.php
src/Command/MappingListClassesCommand.php
src/Metadata/Driver/AnnotationDriver.php
tests/Command/MappingDebugClassCommandTest.php
tests/Kernel/FilesystemAppKernel.php
tests/Kernel/FlysystemOfficialAppKernel.php
tests/Kernel/FlysystemOneUpAppKernel.php
tests/Kernel/SimpleAppKernel.php
tests/Metadata/Driver/AnnotationDriverTest.php

Make getAllClassNames in AnnotationDriver return a list of Doctrine managed entities that are annotated with `@Vich\Uploadable` by injecting `Doctrine\Persistence\ManagerRegistry` (Service ID `doctrine` in a Symfony app), making `vich:mapping:list-classes` discover that entities.
Also provides autocompletion for `vich:mapping:debug-class` (fix #1232)
[![asciicast](https://asciinema.org/a/510200.svg)](https://asciinema.org/a/510200)

Implement getAllClassNames in AnnotationDriver

---

src/Entity/File.php

When normalizing the File the `getWidth` and `getHeight` are called and while the dimension for null files is returned as an empty array the original check is not enough to handle this case.

#1308 Handle empty dimensions array case

---

composer.json
docs/index.md
docs/other_usages/replacing_file.md
docs/usage.md
src/FileAbstraction/ReplacingFile.php
src/Handler/UploadHandler.php
src/Mapping/PropertyMapping.php
src/Naming/OrignameNamer.php
src/Naming/Polyfill/FileExtensionTrait.php
src/Storage/AbstractStorage.php
src/Storage/FileSystemStorage.php
src/Storage/FlysystemStorage.php
src/Storage/GaufretteStorage.php
tests/Storage/FileSystemStorageTest.php
tests/Storage/StorageTestCase.php
tests/TestCase.php
tests/VichUploaderBundleTest.php

This fixes #1296.
I removed most of the dependencies of files in `/src/Storage` on `UploadedFile` because it makes no sense in my opinion.
Going beyond this PR I even think that [this](https://github.com/dustin10/VichUploaderBundle/blob/6b8ac89b54ee8340e3fc108927b2c20226118436/src/Storage/FileSystemStorage.php#L21) should be replaced with a copy call, because all other concrete implementations of `Storage` indeed only copy and do not remove the original. In practice this might not be relevant though.
The new class `ReplacingFile` provides a method `getClientOriginalName` to be somewhat compatible with `UploadedFile`.  I changed all other occurrences of `UploadedFile` to alternatively expect an `ReplacingFile`. If language level would be PHP 8.1., this could be a union type in all …

Added support for 'ReplacingFile' to 'upload' files not uploaded via HTTP

---

src/Storage/FileSystemStorage.php
tests/Storage/FileSystemStorageTest.php

I guess the `FileSystemStorage` just lacked functionality for `DirectoryNamerInterface`/subdirectories. Don't know how this issue has not come up earlier...

Fixes issue #1316

---

src/Command/MappingDebugClassCommand.php
src/Command/MappingDebugCommand.php
src/Command/MappingListClassesCommand.php
tests/Kernel/FilesystemAppKernel.php
tests/Kernel/FlysystemOfficialAppKernel.php
tests/Kernel/FlysystemOneUpAppKernel.php
tests/Kernel/SimpleAppKernel.php

Backporting some of the v2.0 changes into 1.x branch:
- removing `$defaultName` from Command classes
- setting `framework.http_method_override` in tests

Fix command and Symfony deprecations

---

UPGRADE.md

It took me quite some time to figure auf why our mappings are not working anymore. So I've added some help for users who want to upgrade but are still using annotations. I think this will save others some time.

Hint for annotation usage in UPGRADE.md

---

composer.json
config/gaufrette.xml

Classes that are final cannot be marked as lazy.
This service was originally marked as lazy with https://github.com/dustin10/VichUploaderBundle/pull/630, but I cannot reproduce a circular reference with my project after removing the lazy flag.

Remove lazy flag from GaufretteStorage

---

config/factory.xml
src/Mapping/PropertyMappingFactory.php
src/Mapping/PropertyMappingResolver.php
src/Mapping/PropertyMappingResolverInterface.php
tests/Mapping/PropertyMappingFactoryTest.php

This refactors parts of the property mapping factory into a resolver to allow for decoration via an interface.
Refs #1317

Refactor property mapping creation into a class

---

composer.json

With Doctrine MongoDB ODM 1.x no longer being supported, this library no longer relies on the deprecated `ext-mongo` extension, so we no longer need to install the polyfill for it.

Remove ext-mongo polyfill

---

docs/mapping/xml.md
vich_uploader.xsd

Provides an XSD schema so that creating XML mapping is easier, since IDE can use it for autocompletion
|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no
Creating an XML document without an associated XSD schema is error prone. With the provided XSD schema, IDEs can provide autocompletion, and XML files can be validated.

XSD schema for XML mapping

---

UPGRADE.md
composer.json
docs/known_issues.md

As discussed in #1344 , before finding a proper way to deal with this issue, i propose to update the documentation & package suggestion.
This way, developpers encoutering this issue will have an easy way to solve it until we implement a more independant solution

:pencil: (Doctrine) Update docs & package suggestions

---

docs/downloads/serving_files_with_a_controller.md

Fix a missing folder in the link to the DownloadHandler file on the Serving files with a controller README.

Docs: Fix DownloadHandler link

---

src/Mapping/PropertyMapping.php
src/Mapping/PropertyMappingFactory.php
src/Naming/CurrentDateTimeDirectoryNamer.php
src/Naming/DirectoryNamerInterface.php
src/Naming/PropertyDirectoryNamer.php
src/Naming/SubdirDirectoryNamer.php
src/Storage/AbstractStorage.php
src/Templating/Helper/UploaderHelper.php
src/Templating/Helper/UploaderHelperInterface.php
src/Twig/Extension/UploaderExtensionRuntime.php
src/Util/PropertyPathUtils.php

Closes #1361.
This PR (re)allows the use of an array instead of an object to resolve a file path. I also went ahead and reintroduced this feature for the twig filter.
I moved the `fixPropertyPath` function to a utils file since it was also needed in the `directoryName` function because of the date property contained in the array.

Allow use of array to resolve uri

---

.github/workflows/build.yaml
UPGRADE.md
composer.json
src/DependencyInjection/Compiler/RegisterMappingDriversPass.php
src/DependencyInjection/VichUploaderExtension.php
src/Metadata/Driver/AnnotationDriver.php
src/Metadata/Driver/AttributeReader.php
tests/Command/MappingDebugCommandTest.php

do not rely on annotations to use attributes

---

src/Twig/Extension/UploaderExtensionRuntime.php

Symfony will trigger a deprecation warning even when calling `vich_uploader_asset` with a single parameter because UploaderExtensionRuntime::asset passes always 3 parameters.

Fix deprecation warning on 1.x

---

docs/usage.md

Add file property for Doctrine Embedded example to show how to map fields

Update example with Embedded

---

.github/workflows/build.yaml
src/DependencyInjection/Configuration.php
tests/DependencyInjection/VichUploaderExtensionTest.php
tests/Kernel/FlysystemOfficialAppKernel.php
tests/Kernel/FlysystemOneUpAppKernel.php

fix configuration

---

src/Form/Type/VichImageType.php

This commit updates the VichImageType class by removing the 'final' keyword, thereby allowing for extension of the class. This modification maintains consistency with Symfony's practice of non-final form types, enabling developers to extend this form type to add custom functionality or modifications as needed.

Refactor: Make VichImageType class extensible by removing 'final'

---

src/Storage/FlysystemStorage.php
tests/Storage/Flysystem/AbstractFlysystemStorageTest.php

It resolves a lot of problems related to Flysystem.
Without this PR, if we are using S3, Cloudflare images or other cloud storage, the public url is not the CDN one but a local url which is incorrect.
For the people who will suggest using `uri_prefix`, as I mentionned here: https://github.com/dustin10/VichUploaderBundle/issues/1434#issuecomment-2041172155
In my case it is impossible to add `uri_prefix` manually, because in Cloudflare, the file name is not at the end, it is something like `https://imagedelivery.net/qsdazd54azd98a4z69d5/image3.jpg/public` the `/public` at the end makes it impossible because it is not just a prefix, we have to do some sprintf etc.
The problem existe since more than 8 years, I think it is time to automatise it with this PR.
I hope that it will be ok for …

Add missing resolveUri method to FlysystemStorage

---

docs/storage/flysystem.md
src/Storage/FlysystemStorage.php
tests/Storage/Flysystem/AbstractFlysystemStorageTest.php

It looks like it is a breaking change, as mentionned by 3 people here: https://github.com/dustin10/VichUploaderBundle/pull/1441
Maybe in the future it will be implemented in a major release (I hope)

Revert changes of #1441

---

docs/events/events.md
src/Event/ErrorEvent.php
src/Event/Events.php
src/Handler/UploadHandler.php
src/Storage/FileSystemStorage.php
src/Storage/FlysystemStorage.php
src/Storage/GaufretteStorage.php
src/Storage/StorageInterface.php
tests/Handler/UploadHandlerTest.php
tests/Storage/FileSystemStorageTest.php
tests/Storage/GaufretteStorageTest.php

If the underlying storage fails, we emit an event that can be handled as the user wants.
The behaviour is to throw exceptions on write but not on remove as this seems to be the semantics as they are in the library prior to this change.
It seems to me that the error behavior of remove operations is a bit uneven. If a write fails in the native filesystem it seems to me that that will trigger some kind of error.
Anyhow, I think this keeps BC but introduces an event.
Ref #1449

If the underlying storage fails, emit an event

---

config/flysystem.xml
docs/storage/flysystem.md
src/DependencyInjection/Configuration.php
src/DependencyInjection/VichUploaderExtension.php
src/Storage/FlysystemStorage.php
tests/Storage/Flysystem/AbstractFlysystemStorageTest.php

Based on the work of @sovetski in #1441 the PR will allow you to optionally have FlysystemStorage return the public URL of the filesystem instead. Doing it like this makes the new behaviour become opt-in and it does not require a new major version to release.
To enable simply add a configuration variable:
```diff
vich_uploader:
db_driver: orm
metadata:
type: attribute
storage: 'flysystem'
+   use_flysystem_to_resolve_uri: true
```

Optionally resolve the uri through flysystem

---

templates/Collector/icon.svg

This was bothering me :P 
Like symfony's own icons the svg itself should not have the `icon` and `icon-tabler` classes as these are applied in the template (https://github.com/symfony/symfony/tree/7.1/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Icon).

Fix the aligment of the icon in the symfony profiler

---

config/namer.xml
docs/namers.md
src/Naming/ConfigurableDirectoryNamer.php
tests/Naming/ConfigurableDirectoryNamerTest.php

---
name: ⚙ Improvement
about: Allowing to set the image subfolders directly from the yaml configuration (without having to rely on property accessor)
---
|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no
This pr is a proposal to add a new directory namer, which allow to configure the image subfolders directly from the yaml configuration.
This would allow to use multiple vich mapping on the same storage, without 
- having to duplicate the storage configuration for each mapping
- be forced to use the PropertyDirectoryNamer, which add a method solely for this purpose
For example, it would allow to do the following: 
```
vich_uploader:
storage: flysystem
mappings:
logo:
uri_prefix: '%app.uploads.uri_prefix%'
upload_destination: …
```

Allow creating directory subfolders by giving the path in the config

---

.github/workflows/build.yaml
composer.json
docker/Dockerfile81
docker/Dockerfile82
docker/Dockerfile83
tests/Handler/UploadHandlerTest.php
tests/Storage/Flysystem/AbstractFlysystemStorageTestCase.php
tests/Storage/Flysystem/MountManagerFlysystemStorageTest.php
tests/Storage/Flysystem/PsrContainerFlysystemStorageTest.php

This PR solves more deprecations of phpunit, so we can try to upgrade phpunit to version 10 (and maybe 11)
Still, the upgrade is likely not possible due to the incompatibility of the symfony bridge.
Moreover, this PR moves the restrictions of the http-kernel versions to test only, so the user can upgrade to more recent versions. In the tests, recent versions cause failures in our kernel-based tests

✅ remove other phpunit deprecations

---

src/FileAbstraction/ReplacingFile.php
src/Storage/AbstractStorage.php

When I download a file from some source and want to add it to an entity, I use ReplacingFile and it creates the file according to the naming rules, but the downloaded file remains as well. I would like to be able to delete the downloaded file if needed.

Ability to remove file for ReplacingFile

---

src/Storage/FlysystemStorage.php
tests/Storage/Flysystem/AbstractFlysystemStorageTestCase.php

Related to #1445
Add handling for UndefinedMethodError exception in FlysystemStorage.
* Catch both `FilesystemException` and `UndefinedMethodError` exceptions in the `publicUrl` method of `src/Storage/FlysystemStorage.php`.
* Add a test case in `tests/Storage/Flysystem/AbstractFlysystemStorageTestCase.php` to check for `UndefinedMethodError` exception handling in the `resolveUri` method.
* Ensure the test case covers both exceptions to maintain compatibility with different Flysystem versions.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/dustin10/VichUploaderBundle/issues/1445?shareId=23df5f4d-8611-4598-bf4d-508b46f3196e).

Fix exception handling in FlysystemStorage

---

src/Naming/OrignameNamer.php
tests/Naming/OrignameNamerTest.php

🐛 fix double extension in namer

---

CONTRIBUTING.md
docker/Dockerfile83
docker/Dockerfile84
tests/DependencyInjection/VichUploaderExtensionTest.php
tests/DummyFile.php
tests/DummyImageFile.php
tests/Fixtures/App/app/config/config.yml
tests/Metadata/Driver/AnnotationDriverTest.php

🎨 remove annotations from tests

---

UPGRADE.md
src/Naming/Polyfill/FileExtensionTrait.php
tests/Naming/SmartUniqidNamerTest.php

🐛 address extension change in the code and in the docs

---

src/Storage/FlysystemStorage.php
tests/Storage/Flysystem/AbstractFlysystemStorageTestCase.php

This PR needs #1486 before to be merged.
When using publicUri with flysystem, it could be necessary to have more context (the object, mapping and fieldName) to generate a public uri

Improve public uri

---

src/Storage/AbstractStorage.php
src/Storage/FileSystemStorage.php
src/Storage/FlysystemStorage.php
src/Storage/GaufretteStorage.php
tests/Storage/FileSystemStorageTest.php
tests/Storage/Flysystem/AbstractFlysystemStorageTestCase.php
tests/Storage/GaufretteStorageTest.php

Fixes #1533
Fixes issue where directories literally named `"0"` are incorrectly omitted from file URIs and paths when using `SubdirDirectoryNamer`. The problem occurs because
`empty($uploadDir)` incorrectly treats the string `"0"` as empty.
When `SubdirDirectoryNamer` generates a subdirectory named `"0"`, it gets dropped from the URI:
- **Expected**: `/uploads/0/filename.jpg`
- **Actual**: `/uploads/filename.jpg`
Multiple storage classes use `empty($dir)` which returns `true` for the string `"0"`:
- `FileSystemStorage::resolveUri()` and `doResolvePath()`
- `AbstractStorage::resolveUri()`
- `GaufretteStorage::doUpload()`, `doRemove()`, `doResolvePath()`
- `FlysystemStorage::doUpload()`, `doRemove()`, `doResolvePath()`
Replaced `empty($dir)` with `is_string($dir) && $dir !== ''` across all …

Fix directories named "0" being dropped in storage URI resolution

---

config/factory.xml
config/handler.xml
src/EventListener/Doctrine/BaseListener.php
src/Form/Type/VichFileType.php
src/Form/Type/VichImageType.php
src/Handler/AbstractHandler.php
src/Handler/DownloadHandler.php
src/Handler/DownloadHandlerInterface.php
src/Handler/UploadHandler.php
src/Handler/UploadHandlerInterface.php
src/Mapping/PropertyMappingFactory.php
src/Mapping/PropertyMappingFactoryInterface.php
src/Storage/AbstractStorage.php
src/Storage/FlysystemStorage.php
src/Storage/GaufretteStorage.php

The DB Finals bypass is not 100% reliable. Providing interfaces instead allows for mocking without additional complex hooks modifying the PHP environment.
This adds interfaces and default service aliases so there are no changes required.

Add interfaces for easier testing
